(function(){
  function pad3(n){ n=Number(n)||0; return String(n).padStart(3,'0'); }
  async function buildPrettyMapForDate(planDate){ var res=await api({action:'v2_inbound_plan_list',start_date:planDate,end_date:planDate,status:''}); var items=(res&&res.ok&&res.items)?res.items.slice():[]; items.sort(function(a,b){ var ta=String(a.created_at||''); var tb=String(b.created_at||''); if(ta===tb) return String(a.id||'').localeCompare(String(b.id||'')); return ta.localeCompare(tb); }); var map={}; items.forEach(function(it,idx){ map[it.id]='RU-'+String(planDate||'').replace(/-/g,'')+'-'+pad3(idx+1); }); return map; }
  async function prettyInboundNoById(id,planDate){ if(!id||!planDate) return id||''; var map=await buildPrettyMapForDate(planDate); return map[id]||id; }
  function stripDiffRequired(){ var diffArea=document.getElementById('unloadDiffArea'); if(!diffArea) return; var lbl=diffArea.querySelector('label'); if(lbl) lbl.textContent='差异备注（可选） / 차이 메모(선택)'; }
  window.loadInboundPlans = async function(selectId){ var sel=document.getElementById(selectId); if(!sel) return; var res=await api({action:'v2_inbound_plan_list',start_date:'',end_date:'',status:''}); var items=(res&&res.ok&&res.items)?res.items.slice():[]; var byDate={}; items.forEach(function(p){ if(p.status==='completed'||p.status==='cancelled') return; var d=p.plan_date||''; if(!byDate[d]) byDate[d]=[]; byDate[d].push(p); }); var opts='<option value="">-- 选择入库计划/입고계획 선택 --</option>'; Object.keys(byDate).sort().reverse().forEach(function(d){ byDate[d].sort(function(a,b){ var ta=String(a.created_at||''); var tb=String(b.created_at||''); if(ta===tb) return String(a.id||'').localeCompare(String(b.id||'')); return ta.localeCompare(tb); }); byDate[d].forEach(function(p,idx){ var pretty='RU-'+String(d||'').replace(/-/g,'')+'-'+pad3(idx+1); opts+='<option value="'+esc(p.id)+'">['+pretty+'] '+esc(p.customer||'')+' - '+esc(p.cargo_summary||'')+'</option>'; }); }); sel.innerHTML=opts; };
  var _origShowUnloadWorking=window.showUnloadWorking; window.showUnloadWorking=function(job){ _origShowUnloadWorking(job); stripDiffRequired(); if(_unloadPlanData&&_unloadPlanData.plan){ prettyInboundNoById(_unloadPlanData.plan.id,_unloadPlanData.plan.plan_date).then(function(pretty){ var info=document.getElementById('unloadPlanInfo'); if(!info||!pretty) return; var p=_unloadPlanData.plan; info.innerHTML='<div><b>'+esc(pretty)+'</b> | '+esc(p.plan_date)+' | '+esc(p.customer)+'</div><div class="muted">'+esc(p.cargo_summary||'')+(p.remark?' — '+esc(p.remark):'')+'</div>'; }); } };
  var _origInitUnload=window.initUnload; window.initUnload=async function(){ await _origInitUnload(); stripDiffRequired(); };
  window.unloadComplete = async function(){ if(!_activeJobId) return; var resultLines=getUnloadResultLines(); if(resultLines.length===0){ alert('请至少填写一项实际数量 / 실제 수량을 최소 1건 입력하세요'); return; } var planLines=(_unloadPlanData&&_unloadPlanData.lines)||[]; var diffNote=((document.getElementById('unloadDiffNote')||{}).value||'').trim(); if(planLines.length>0){ var hasDiff=false; var actualMap={}; resultLines.forEach(function(r){ actualMap[r.unit_type]=r.actual_qty; }); planLines.forEach(function(ln){ if((actualMap[ln.unit_type]||0)!==(ln.planned_qty||0)) hasDiff=true; }); if(hasDiff&&!diffNote){ diffNote='现场实收数量与计划数量不一致'; } } var remark=((document.getElementById('unloadRemark')||{}).value||'').trim(); var res=await api({action:'v2_unload_job_finish',job_id:_activeJobId,worker_id:getWorkerId(),result_lines:resultLines,diff_note:diffNote,remark:remark,complete_job:true}); if(res&&res.ok){ var msg='卸货已完成 / 하차 완료'; if(res.no_doc) msg+='\n（无单卸货已自动生成反馈 / 서류 없는 하차 피드백 자동 생성됨）'; alert(msg); clearActiveJob(); _unloadPlanData=null; goPage('home'); } else if(res&&res.error==='others_still_working'){ alert('还有'+res.active_count+'人参与中，无法完成 / 아직 '+res.active_count+'명 참여 중, 완료 불가'); } else if(res&&res.error==='empty_result'){ alert(res.message||'至少填写一项实际数量'); } else if(res&&res.error==='diff_note_required'){ alert('系统仍要求差异备注，已记录默认说明后请重试 / 시스템이 차이 메모를 요구합니다'); } else { alert('失败/실패: '+(res?res.error:'unknown')); } };
  document.addEventListener('DOMContentLoaded',stripDiffRequired);
})();